:hammer: Wayland support for electron apps
flathub-infra/ide-flatpak-wrapper pull request #23
Opened 2024-02-22 19:12 UTC by noonsleeper

2024-05-08 07:36 UTC, daiyam commented
Hello @gasinvein, can you give us a timeline for this PR? Thx

2024-05-08 09:30 UTC, gasinvein commented
Hello, sorry for the delay and thanks for the contribution. Sadly, I cannot test this myself atm. Did you try to build VSCod[ium] flatpak with this wrapper version and verify that it works as intended?

2024-05-08 10:00 UTC, gasinvein requested changes

2024-05-08 10:34 UTC, daiyam commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
> Isn't checking if `XDG_SESSION_TYPE` is set to `wayland` is enough?

No, under KDE, `$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY` will give `/run/user/1000//run/flatpak/wayland-0` which is incorrect. That's why @noonsleeper is testing for the prefix `/run/flatpak/wayland-`.

2024-05-08 10:45 UTC, daiyam commented
> Hello, sorry for the delay and thanks for the contribution. Sadly, I cannot test this myself atm. Did you try to build VSCod[ium] flatpak with this wrapper version and verify that it works as intended?

No problem. :)

The latest version should include it with the fix for KDE but I haven't test it myself... 
But VSCodium has been using with the PR since the March releases.

2024-05-08 11:48 UTC, bbhtt commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
Checking for the socket is correct, `$XDG_SESSION_TYPE` can stay on wayland even if the finish arg is removed (ie. with `--nosocket`) as it is inherited from the environment and has no connection with the active finish args.

> /run/user/1000//run/flatpak/wayland-0

These two are symlinks it should not overlap like that. If `WAYLAND_DISPLAY` is an absolute path it is used as is since https://github.com/flatpak/flatpak/pull/4752

It's here now https://github.com/flatpak/flatpak/blob/739065e432ac9c0161ec5387b6a52cad10fc4527/common/flatpak-run-wayland.c#L43-L44

If not, it is relative to the `XDG_RUTNIME_DIR`

You should check for only one of them.

2024-05-08 11:54 UTC, bbhtt commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
If you want to make it more sound you can check if `stat -c %F /run/flatpak/wayland-0` reports `socket` or if it fails.

2024-05-08 15:33 UTC, noonsleeper commented on editor.sh
> +  exec "@WRAPPER_PATH@" @EDITOR_ARGS@ $(display_server_args) ${EDITOR_RUNTIME_ARGS} "$@"
Hi @gasinvein, I'll do

2024-05-08 16:25 UTC, bbhtt commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
I think you can just assume that `/run/flatpak/wayland-{0, 1, ...}` is present and check if only that one exists.

https://github.com/flatpak/flatpak/blob/739065e432ac9c0161ec5387b6a52cad10fc4527/common/flatpak-run-wayland.c#L265-L270 part ensures that if WAYLAND_DISPLAY is an absolute path it gets set to `wayland-0`

2024-05-08 16:54 UTC, bbhtt commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
Also don't think `-e` supports pattern matching like that, your first condition always fails (it is checking for `/run/flatpak/wayland-`.

![image](https://github.com/flathub-infra/ide-flatpak-wrapper/assets/62639087/1832bc3f-1f54-4101-ba8e-77266f5e2c78)

2024-05-08 17:18 UTC, bbhtt commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
You can do `if [[ -e "$(echo "/run/flatpak/wayland-"*)" ]]; then echo "yes"; else echo "no"; fi` but it might match `wayland-0.lock` too

2024-05-09 00:20 UTC, noonsleeper commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
@bbhtt, @gasinvein

I'm still on Silverblue F39 and `WAYLAND_DISPLAY` is reporting only `wayland-0` not the full path, I don't check if F40 change that behaviour within gnome 46, but I think other distros like Debian or Ubuntu maybe has the same behaviour for Gnome 45.
Then, if we need to check both at the same time, I come with this:

![Screenshot from 2024-05-08 20-44-30](https://github.com/flathub-infra/ide-flatpak-wrapper/assets/62183384/128b2ff3-fd1c-4f63-864f-b3df1930629f)

It is not perfect like you can see, but it comes handy because I don't use or pass that variable to anything, also this check that at least the variable is filled with something that resembles what we are looking for,

Also, I can go with a more accurate regex that only `*wayland-?` (to me this will add more complexity to something that doesn't require that, but maybe I'm wrong, I'm open to any advice), what do you think? 

Btw, sorry for this wall of text

2024-05-09 01:49 UTC, dbnicholson commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
I think it would be easier to check if `WAYLAND_DISPLAY` is an absolute path. If not, then construct the path to the socket using the implicit path. Like:

```
local display_type=x11
local display_server_args
local wayland_socket

if [ "$XDG_DISPLAY_TYPE" = wayland ] && [ -n "$WAYLAND_DISPLAY" ]; then
    if [[ $WAYLAND_DISPLAY =~ ^/ ]]; then
        wayland_socket=$WAYLAND_DISPLAY
    else
        wayland_socket="${XDG_RUNTIME_DIR:-/run/user/${UID}}/${WAYLAND_DISPLAY}"
    fi

    [ -e "$wayland_socket" ] && display_type=wayland
fi

if [ "$display_type" = wayland ]; then
    # Set display_server_args for wayland
else
    # Set display_server_args for x11
fi

echo $display_server_args
```

2024-05-09 01:52 UTC, dbnicholson commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
Another way without using a regex would be `[ "${WAYLAND_DISPLAY::1}" = / ]`.

2024-05-09 02:09 UTC, bbhtt commented on editor.sh
> +  if [[ ${WAYLAND_DISPLAY} == "/run/flatpak/wayland-"* ]] || [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]] && [[ "wayland" == "${XDG_SESSION_TYPE}" ]]
> I think it would be easier to check if WAYLAND_DISPLAY is an absolute path. If not, then construct the path to the socket using the implicit path. Like:

This also works I think.

2024-05-26 05:33 UTC, noonsleeper commented on editor.sh
> +  exec "@WRAPPER_PATH@" @EDITOR_ARGS@ $(display_server_args) ${EDITOR_RUNTIME_ARGS} "$@"
@gasinvein is already done

2024-06-08 18:54 UTC, noonsleeper commented
Hi @gasinvein, Can you give me an update about this?

2024-06-08 19:15 UTC, gasinvein approved these changes
LGTM.

2024-06-08 19:15 UTC, merged

2024-06-08 19:17 UTC, gasinvein commented
The `zypak` branch was in a WiP state, but it seems like several apps on Flathub started using it. Do you folks consider it ready? If so, should we merge it into the main branch (see #13)?

2024-06-08 19:57 UTC, noonsleeper commented
> The `zypak` branch was in a WiP state, but it seems like several apps on Flathub are using it now. Do you folks consider it ready? If so, should we merge it into the main branch (see #13)?

I was using this since nearly the creation of the branch, and at least for codium and codium-insiders it works like a charm.

2024-06-09 07:52 UTC, gasinvein commented on editor.sh
> +  exec "@WRAPPER_PATH@" @EDITOR_ARGS@ $(display_server_args) ${EDITOR_RUNTIME_ARGS} "$@"
@noonsleeper Ok, there seems to be one thing I've missed. The wrapper isn't solely for Electron apps, thus electron-specific cli args shouldn't be added unconditionally.
Adding the display server args for electron should be gated behind Zypak feature being enabled.

2024-06-09 16:20 UTC, noonsleeper commented on editor.sh
> +  exec "@WRAPPER_PATH@" @EDITOR_ARGS@ $(display_server_args) ${EDITOR_RUNTIME_ARGS} "$@"
Then I will make a new PR